name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install
      - run: node --run prettier
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install
      - run: node --run eslint
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install
      - run: node --run types
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [20, 22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test
        if: matrix.node < 22
      - run: node --run test
        if: matrix.node >= 22
